### PR TITLE
fixes `.stack` on firefox

### PR DESCRIPTION
**Pull request by simonzack**
fixes chaijs/chai#100.

### CODE REVIEW

**Comment by simonzack** [comment]
Hmm travis is reporting "Error: No compatible version found: component-pin@'^1.0.4'", don't think it's related to this change.

**Comment by simonzack** [comment]
@keithamus can you please take a look? Thanks.

**Comment by simonzack** [comment]
Bump, patch is really simple, should only take a second, thanks!

**Comment by keithamus** [comment]
@simonzack sorry - I somehow missed this one! Looks like the build failed, but may be unrelated. I've re-run it. If it passes I'll merge.

**Comment by keithamus** [comment]
Still failing. Could you try rebasing @simonzack?

**Comment by simonzack** [comment]
@keithamus Thanks for taking a look. I just pulled and it is based on the latest commit (from 2013). The build does succeed for node v0.10 but fails for v.0.8, where the logs say that component could not be installed. The component page says it only supports node v0.10.

**Comment by keithamus** [comment]
@simonzack it sounds like something might be going a bit wrong here. Can I suggest you run the following:

```bash
git remote rm upstream
git remote add upstream https://github.com/chaijs/assertion-error.git
git fetch -p upstream
git rebase upstream/master
git push origin master
```

**Comment by simonzack** [comment]
@keithamus But isn't cb277d2 the latest commit on master? This is what the [git hub page](https://github.com/chaijs/assertion-error) says, "latest commit cb277d2aa5
Jake Luer logicalparadox authored on 9 Jun 2013 "

**Comment by keithamus** [comment]
Oh duh... I'm totally getting confused between repos now. Sorry @simonzack :blush:.

I think this is probably failing because of the fact Component no longer supports 0.8... We could probably drop support for 0.8 as no longer "officially" supported anyway. We dropped suport for 0.8 around the end of 2013 on mainline chai anyway: https://github.com/chaijs/chai/commit/678c63e9c22aaaa29f66e686bad1ee5e3f776069.

I'll merge this one - despite the failures, and work on getting a new release which drops support.

**Comment by simonzack** [comment]
Great, looking forward to it! :)

**Pull request merged**
